AllCops:
  DisplayCopNames: true
Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/ClassLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 14
Metrics/BlockLength:
  Max: 40
