Metrics/MethodLength:
  Max: 200
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/ClassLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 14
